import datetime
from typing import Callable, Any, Literal, overload, ClassVar, Protocol, Optional

from abstract.apis.table import Table


class Registerable(Protocol):
    """可注册为类属性的对象：必须拥有 __name__ 并实现描述符协议。"""
    __name__: str
    def __get__(self, instance: Any, owner: type | None = None) -> Any: ...


class User:
    role: Literal["member", "admin", "owner", "operator"]
    init_tables: ClassVar[list[Table]]
    registered_options: list[str]
    id: int
    name: str
    """
    用户角色:
    - member: 普通成员
    - admin: 群管理员
    - owner: 群主
    - operator: Bot操作员（最高权限）
    """

    @overload
    def __init__(self, data: dict) -> None: ...

    @overload
    def __init__(self, id: int | str) -> None: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, value: object) -> bool: ...

    def __hash__(self) -> int: ...

    @classmethod
    def register_attr[T: Registerable](cls, func: T) -> T: ...

    @classmethod
    def register_option(cls, option_name: str) -> property: ...

    @property
    def points(self) -> int: ...

    @points.setter
    def points(self, value: int) -> None: ...

    @property
    def sign_date(self) -> datetime.date: ...

    @sign_date.setter
    def sign_date(self, value: datetime.date): ...

    def update_sign_date(self): ...

    def game_data_exist(self, game: str) -> bool: ...

    def game_data_init(self, game: str): ...

    @staticmethod
    def check_game_data[T: Callable[[User, Any], Any]](func: T) -> T: ...

    def get_game_data(self, game: str) -> dict: ...

    def get_game_info(self, game: str) -> dict: ...

    def win_game(self, game: str) -> None: ...

    def draw_game(self, game: str) -> None: ...

    def lose_game(self, game: str) -> None: ...

    @property
    def game_blacklist(self) -> set[User]: ...

    @game_blacklist.setter
    def game_blacklist(self, value: set[User]) -> None: ...


class Group:
    id: int
    name: str
    registered_options: list[str]
    def __init__(self, id: int) -> None: ...

    @property
    def members(self) -> set[User]: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, value: object) -> bool: ...

    def __hash__(self) -> int: ...

    def __contains__(self, value: User) -> bool: ...

    @classmethod
    def register_attr[T: Registerable](cls, func: T) -> T: ...

    @classmethod
    def register_option(cls, option_name: str) -> property: ...

    @property
    def trusted(self) -> bool: ...

    @trusted.setter
    def trusted(self, value: bool): ...

    @property
    def r18(self) -> bool: ...

    @r18.setter
    def r18(self, value: bool): ...

    @property
    def recall_catch(self) -> bool: ...

    @recall_catch.setter
    def recall_catch(self, value: bool): ...

    @property
    def city(self) -> Optional[str]: ...

    @city.setter
    def city(self, value: Optional[str]): ...

    @property
    def night_disturb(self) -> bool: ...

    @night_disturb.setter
    def night_disturb(self, value: bool): ...
